name: Build

on: [push]

jobs:

  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    name: '${{ matrix.platform }}'
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install go 1.22
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: |
          make build/vidx2pidx
          make OS=windows ARCH=amd64 build/vidx2pidx.exe
          make clean
          make OS=darwin  ARCH=amd64 build/vidx2pidx
          make clean
          make OS=windows ARCH=arm64 build/vidx2pidx.exe
          make clean
          make OS=darwin  ARCH=arm64 build/vidx2pidx
          make clean
          make OS=linux  ARCH=arm64 build/vidx2pidx

      - name: Build executables
        run: |
          GOOS=windows GOARCH=amd64 go build -o build/win-amd64/vidx2pidx.exe ./cmd
          GOOS=windows GOARCH=arm64 go build -o build/win-arm64/vidx2pidx.exe ./cmd
          GOOS=darwin GOARCH=amd64 go build -o build/mac-amd64/vidx2pidx ./cmd
          GOOS=darwin GOARCH=arm64 go build -o build/mac-arm64/vidx2pidx ./cmd
          GOOS=linux GOARCH=amd64 go build -o build/lin-amd64/vidx2pidx ./cmd
          GOOS=linux GOARCH=arm64 go build -o build/lin-arm64/vidx2pidx ./cmd

      - name: Archive windows amd64 binaries
        uses: actions/upload-artifact@v4
        with:
          name: vidx2pidx-windows-amd64
          path: ./build/win-amd64/vidx2pidx.exe
          retention-days: 1
          if-no-files-found: error

      - name: Archive windows arm64 binaries
        uses: actions/upload-artifact@v4
        with:
          name: vidx2pidx-windows-arm64
          path: ./build/win-arm64/vidx2pidx.exe
          retention-days: 1
          if-no-files-found: error

      - name: Archive macos amd64 binaries
        uses: actions/upload-artifact@v4
        with:
          name: vidx2pidx-mac-amd64
          path: ./build/mac-amd64/vidx2pidx
          retention-days: 1
          if-no-files-found: error

      - name: Archive macos arm64 binaries
        uses: actions/upload-artifact@v4
        with:
          name: vidx2pidx-mac-arm64
          path: ./build/mac-arm64/vidx2pidx
          retention-days: 1
          if-no-files-found: error

      - name: Archive linux amd64 binaries
        uses: actions/upload-artifact@v4
        with:
          name: vidx2pidx-lin-amd64
          path: ./build/lin-amd64/vidx2pidx
          retention-days: 1
          if-no-files-found: error

      - name: Archive linux arm64 binaries
        uses: actions/upload-artifact@v4
        with:
          name: vidx2pidx-lin-arm64
          path: ./build/lin-arm64/vidx2pidx
          retention-days: 1
          if-no-files-found: error
