name: Build

on: [push]

jobs:

  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go: [1.22.x]
    name: '${{ matrix.platform }} | ${{ matrix.go }}'
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: |
          make build/vidx2pidx
          make OS=windows ARCH=amd64 build/vidx2pidx.exe
          make clean
          make OS=darwin  ARCH=amd64 build/vidx2pidx
