name: check copyright
on:
  pull_request:
    paths:
      - '.github/workflows/check-copyright.yml'
      - '.pre-commit-config.yaml'
      - 'scripts/check_copyright_notice.py'
      - '**/*.go'
      - '!**/docs/**/*'
      - '!**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  copyright:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout devtools
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check copyright notice
        run: |
          pip install \
            pre-commit \
            comment-parser>=1.2.3
          pre-commit run --all-files
