name: Test

on: [push, pull_request, workflow_call]

jobs:

  lint:
    name: Lint
    timeout-minutes: 10
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v6
        with:
          # must be specified without patch version
          version: latest

  format:
    name: Format
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go: [1.22.x]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Check formatting
        run: |
          make format-check

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        go: [1.22.x]
    name: '${{ matrix.platform }} | ${{ matrix.go }}'
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Unit testing
        run: |
          make coverage-check
